name: Integración Continua - PHP

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

  - name: Instalar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

   - name: Validar archivos PHP
      run: |
        find . -name "*.php" -print0 | xargs -0 -n1 php -l